name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (smoke only)
        run: |
          pytest -q tests/ -k "not e2e"

      - name: Run E2E tests (manual trigger only)
        if: github.event_name == 'workflow_dispatch'
        run: |
          SELENIUM_RUN_E2E=1 pytest -q tests/test_rss_feed_selenium.py -k e2e
        env:
          # 需要 Chrome 和 chromedriver
          CHROME_BIN: /usr/bin/google-chrome

      - name: Setup Chrome for E2E
        if: github.event_name == 'workflow_dispatch'
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          # chromedriver 會由 selenium 自動管理
